---
- name: copy files to remote system
  hosts: all

  tasks:
    - name: copy files
      copy:
        src: /home/absk/downloads/sample.txt
        dest: /home/absk/downloads/
        owner: root
        mode: 0777
        backup: true
