---
- name: run a script
  hosts: all

  tasks:
    - name: run script
      shell: /home/absk/script/test.sh >> test.log #content from script write in test.log
      args:
        chdir: /home/absk/temp
        creates: test.log

