---
- name: Kill a process
  hosts: all

  tasks:
    - name: Find and kill the nginx process
      ignore_errors: yes
      shell: "pgrep nginx | xargs kill"

    - name: start the service
      service:
        name: nginx
        state: started
